// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using vogels_api.Data;

#nullable disable

namespace vogels_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220223204200_InitializeDatabase")]
    partial class InitializeDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("vogels_api.Models.Birdhouse.Birdhouse", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("BlueprintId")
                        .HasColumnType("int unsigned");

                    b.Property<byte>("Level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("UserId");

                    b.ToTable("Birdhouses");
                });

            modelBuilder.Entity("vogels_api.Models.Birdhouse.BirdhouseBlueprint", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<byte>("BasePlots")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<byte>("MinistryId")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId");

                    b.ToTable("BirdHouseBlueprints");
                });

            modelBuilder.Entity("vogels_api.Models.Law.Law", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("BlueprintId")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("UserId");

                    b.ToTable("Law");
                });

            modelBuilder.Entity("vogels_api.Models.Law.LawBlueprint", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<byte>("MinistryId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Requirement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId");

                    b.ToTable("LawBlueprints");
                });

            modelBuilder.Entity("vogels_api.Models.Minister.Minister", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("Actions")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("CustomName")
                        .HasColumnType("longtext");

                    b.Property<byte>("Happiness")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("MinisterId")
                        .HasColumnType("int unsigned");

                    b.Property<uint?>("Xp")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("MinisterId");

                    b.ToTable("Ministers");
                });

            modelBuilder.Entity("vogels_api.Models.Minister.MinisterBlueprint", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<byte>("BaseActions")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<byte>("MinistryId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Premium")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Trait")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MinistryId");

                    b.ToTable("MinisterBlueprints");
                });

            modelBuilder.Entity("vogels_api.Models.Minister.Ministry", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte?>("Dislikes")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Dislikes");

                    b.ToTable("Ministry");
                });

            modelBuilder.Entity("vogels_api.Models.Tree.Tree", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("BlueprintId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("BlueprintId");

                    b.HasIndex("UserId");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("vogels_api.Models.Tree.TreeBlueprint", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    b.Property<byte>("BasePlots")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("TreeBlueprints");
                });

            modelBuilder.Entity("vogels_api.Models.User.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("AllianceId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("GoldenSeeds")
                        .HasColumnType("bigint unsigned");

                    b.Property<sbyte>("Honour")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MaxTactics")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("Ranking")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("Seeds")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("vogels_api.Models.Birdhouse.Birdhouse", b =>
                {
                    b.HasOne("vogels_api.Models.Birdhouse.BirdhouseBlueprint", "BirdhouseBlueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vogels_api.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BirdhouseBlueprint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vogels_api.Models.Birdhouse.BirdhouseBlueprint", b =>
                {
                    b.HasOne("vogels_api.Models.Minister.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("vogels_api.Models.Law.Law", b =>
                {
                    b.HasOne("vogels_api.Models.Law.LawBlueprint", "LawBlueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vogels_api.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawBlueprint");

                    b.Navigation("User");
                });

            modelBuilder.Entity("vogels_api.Models.Law.LawBlueprint", b =>
                {
                    b.HasOne("vogels_api.Models.Minister.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("vogels_api.Models.Minister.Minister", b =>
                {
                    b.HasOne("vogels_api.Models.Minister.MinisterBlueprint", "MinisterBlueprint")
                        .WithMany()
                        .HasForeignKey("MinisterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MinisterBlueprint");
                });

            modelBuilder.Entity("vogels_api.Models.Minister.MinisterBlueprint", b =>
                {
                    b.HasOne("vogels_api.Models.Minister.Ministry", "Ministry")
                        .WithMany()
                        .HasForeignKey("MinistryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ministry");
                });

            modelBuilder.Entity("vogels_api.Models.Minister.Ministry", b =>
                {
                    b.HasOne("vogels_api.Models.Minister.Ministry", "Self")
                        .WithMany()
                        .HasForeignKey("Dislikes");

                    b.Navigation("Self");
                });

            modelBuilder.Entity("vogels_api.Models.Tree.Tree", b =>
                {
                    b.HasOne("vogels_api.Models.Tree.TreeBlueprint", "TreeBlueprint")
                        .WithMany()
                        .HasForeignKey("BlueprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("vogels_api.Models.User.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TreeBlueprint");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
